steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t",
  "gcr.io/www-rchain-coop-222319/github.com/rchain/rsong-admin:v1.0-SNAPSHOT-$SHORT_SHA",
  "rchain-admin" , "."]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ["push",
 "gcr.io/www-rchain-coop-222319/github.com/rchain/rsong-admin:v1.0-SNAPSHOT-$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - "-n"
  - "prd"
  - "set"
  - "image"
  - "deployment.v1.apps/rsong-admin"
  - "gcr.io/www-rchain-coop-222319/github.com/rchain/rsong-admin:v1.0-SNAPSHOT-$SHORT_SHA",
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=rsong-admin'
