---
apiVersion: v1
kind: Service
metadata:
  name: rsong-admin
  labels:
    app: rsong-admin
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: rsong-admin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsong-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsong-admin
  template:
    metadata:
      labels:
        app: rsong-admin
    spec:
      containers:
      - name: rsong-admin
        image: kayvank/rsong-admin:v1.0-SNAPSHOT-00
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 2
